export { default as LoginPage } from './login/LoginPage'
export { default as RequestPage } from './request/RequestPage'
export { default as MainPage } from './main/MainPage'
export { default as NotFoundPage } from './notFound/NotFoundPage'
export { default as UserPage } from './user/UserPage'
export { default as ContractPage } from './contract/ContractPage'
